name: Build/release

on:
  push:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install castlabs EVS dependencies
        run: |
          python -m pip install --upgrade pip
          pip install castlabs-evs

      - name: Decode and create config.json
        run: echo "${{ secrets.CONFIG_JSON }}" | base64 -d > config.json
        shell: bash

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Sign and publish Electron app
        run: |
          npx electron-builder build --config.extraMetadata.EVS_SIGNING=true --publish always
        env:
          EVS_USERNAME: ${{ secrets.EVS_USERNAME }}
          EVS_PASSWORD: ${{ secrets.EVS_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
